services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./docker/pretix
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - "pretix_data:/data"
      - "./docker/pretix/pretix.cfg:/etc/pretix/pretix.cfg"
      - "./docker/pretix/crontab:/tmp/crontab"
    networks:
      - backend
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      # Router
      - "traefik.http.routers.pretix.rule=Host(`${PRETIX_DOMAIN}`)"
      - "traefik.http.routers.pretix.entrypoints=https"
      - "traefik.http.routers.pretix.tls.certresolver=letsencrypt"
      - "traefik.http.services.pretix.loadbalancer.server.port=80"

  database:
    image: "postgres:17-alpine"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pretix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pretix}
      POSTGRES_DB: ${POSTGRES_DB:-pretix}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - backend

  cache:
    image: "redis:alpine"
    restart: always
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  pretix_data:
    driver: local

networks:
  backend:
    driver: bridge
  coolify:
    external: true
